import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
//@ -> root folder (src folder)

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// like head tag 
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) { //name root layout can be changed as per our wish
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}> 
        
        <Header />
        {children}
        
      </body>
    </html>
  );
}
